### ISSUE TITLE
Some documentation issues from the page: http://rivet.online/doc/understanding-the-rivet-visualization/

### ISSUE THREAD

**Issue by delooper** [rivetTDA/rivet#119]
1)  In the paragraph above the "Persistence Diagram Window" heading:

As the line moves, **the both the barcode in the** Line Selection Window and its persistence diagram representation in the Persistence Diagram Window are updated in real time. 

2) Second paragraph: 

a <= b should mean a_1 <= b_1 and a_2 <= b_2, but you say a_1 <= b_2.

**Comment by mlesnick** [comment]
Thanks Ryan.  We are in the process of updating the documentation.  We incorporate these fixes into the new version.

**Comment by mlesnick** [comment]
I fixed these typos.
