### ISSUE TITLE
number fields in RIVET GUI

### ISSUE THREAD

**Issue by delooper** [rivetTDA/rivet#120]
This is more of an ease-of-use issue than a bug. 

In the number fields in the GUI, say I have 1.2345 in the "Bottom" entry (or any number field) and I use backspace to erase the digit 3.  The field is then (correctly) auto-updated to 1.2450, but you can't then replace the 3 as the field is fixed-width and the insertion is forbidden. 

But if you delete the last digit 5, the field is updated (also correctly) to 1.234, and then you can insert a new numeral at the end. 

If you use the up/down button this peculiarity can be avoided, but if you want to enter the numbers with the keypad, the behaviour is non-intuitive. 

I imagine this is a Qt issue so it probably behaves the same on all machines.  I'm using Ubuntu 18.04, in case it matters.

**Comment by mlesnick** [comment]
Simon has addressed this; see commit b9a2c35.
