### ISSUE TITLE
Feature request: add a cut-off distance parameter to rivet_console

### ISSUE THREAD

**Issue by delooper** [rivetTDA/rivet#121]
I find when I use RIVET for metric space input, I have to change the cut-off distance with the homological dimension of the computation.   It would make life a little easier if the cut-off distance was a rivet_console parameter rather than a line in the input file.  

Perhaps a way to have both, would be to have the cut-off in the input file, but you could override it with a rivet_console parameter.

**Comment by mlesnick** [comment]
This has been addressed in RIVET v 1.1
