### ISSUE TITLE
Simple bifiltration crash

### ISSUE THREAD

**Issue by xoltar** [rivetTDA/rivet#143]
The following bifiltration (from the pyrivet test suite) crashes with SIGSEGV:

bifiltration
x_label
y_label
1  2  4  ; -1  -2  
2  4  5  ; -1  -2  
0  1  3  ; -1  -2  
1  3  4  ; -1  -2  
0  2  3  ; -1  -2  
2  5  3  ; -1  -2  
0  1  2  ; 3  -2  
3  4  5  ; -1  2

**Comment by mlesnick** [comment]
I believe that the issue is with the input file.  A while ago, the bifiltration input format was changed.  To compute homology in dimension j, one must explicitly specify the simplices in dimension j-1,j,and j+1.  RIVET no longer infers the faces from the top dimensional simplices.

**Comment by xoltar** [comment]
Ah, that explains it, thanks! I'll update the test suite then.
