### ISSUE TITLE
rivet.online down or missing?

### ISSUE THREAD

**Issue by xoltar** [rivetTDA/rivet#164]
Hi folks,

I can't seem to connect to https://rivet.online nor http://rivet.online. DNS lookup fails in both cases. Has the documentation site moved or perhaps expired?

Thanks,
Bryn

**Comment by mlwright84** [comment]
Hi Bryn! Mike and I decided to let rivet.online expire a while ago, since weren't really using it. We regretted this decision somewhat afterward, but the domain had become unavailable last time we checked. In any case, the RIVET documentation is at https://rivet.readthedocs.io/en/latest/ .

**Comment by xoltar** [comment]
Hi Matthew! OK, that makes sense. In that case we should update the links and email on the rivettda github organization. I've just changed the URL so the readthedocs URL shows on the landing page https://github.com/rivettda. We should also change the email address (currently info@rivet.online), what should that be?

**Comment by mlwright84** [comment]
Thanks, Bryn, for catching this! I didn't realize that our domain was used at https://github.com/rivettda. The displayed email address could be my school email (wright5@stolaf.edu) or Mike's email, or both. @mlesnick , what do you think?

**Comment by mlesnick** [comment]
I have changed the displayed email to Matthew's.  This is fine for now.
