### ISSUE TITLE
RIVET Crashes with Filtrations with Many Bigrades

### ISSUE THREAD

**Issue by mlesnick** [rivetTDA/rivet#68]
This is an issue with how RIVET is handling exact vs. floating point computation in computing the line arrangement.

Our experience is that working with coarsened filtrations (say 20x20 or coarser) circumvents this bug.

[There was a long discussion of this bug in the earlier issue tracker on bitbucket.  Properly transferring all of this over to here is difficult for several reasons, so I'll simply note that Matthew has identified the cause of the bug and is in the progress of squashing it.]

Matthew has determined that this is due to a numerical error in the implementation of the Bentley-Ottoman algorithm.  The issue is with how RIVET implements hybrid floating-point/exact arithmetic.

**Comment by mlwright84** [comment]
Resolved in Pull Request #107.
