### ISSUE TITLE
Error Dialogue When Opening a Certain Precomputed File

### ISSUE THREAD

**Issue by mlesnick** [rivetTDA/rivet#86]
Originally reported by: **M L (GitHub: [mlesnick](https://github.com/mlesnick))**

----------------------------------------

<img width="1440" alt="1480124423-screen shot 2017-03-29 at 10 56 00 am" src="https://cloud.githubusercontent.com/assets/12559620/25406993/a40a140e-29d6-11e7-9978-75025dfe3ef9.png">

The RIVET output file that causes this problem is called testout.rivet.  It is too large to post here, but is available on upon request.  The input file used to generate this RIVET output 
[is here.](https://github.com/rivetTDA/rivet/files/956534/senate104_edge_list.txt_0.68902_distmat.txt_RIVET_Codensity20thPercentile.txt) This file is derived from a distance matrix from Nina Otter's database of test examples for persistent homology; see [this paper and the references therein](https://arxiv.org/abs/1506.08903).

The computation is H0 with a grid of 150x32.  it is the most finely gridded RIVET file I have been able to compute so far; perhaps the error dialogue is related to the fineness of the grid.

I have only tested this file on OS X so far.

**Comment by xoltar** [comment]
Fixed in #88
