### ISSUE TITLE
Crash in Multi-critical Branch

### ISSUE THREAD

**Issue by mlesnick** [rivetTDA/rivet#94]
[Large_Dist_0_Noise.txt](https://github.com/rivetTDA/rivet/files/1062749/Large_Dist_0_Noise.txt)

The attached (small) data set reliably crashes the multicritical version of RIVET (in Roy's fork, not yet in main) with 20x0 bins H0.

Here is the relevant part of the console output (-V 8)

console:  Edge weights computed; this took  27  milliseconds. 

console:  PROGRESS 75

console:  Found path through the arrangement; this took  1  milliseconds. 

console:  STAGE

console:  STEPS_IN_STAGE 312

console:  STORING MULTIGRADES: low = 1 

console:  STORING MULTIGRADES: low = 0 

console:  rivet_console(3620,0x7fffb8c0d3c0) malloc: *** error for object 0x7ff3c4019200: incorrect checksum for freed object - object was probably modified after being freed.

console:  *** set a breakpoint in malloc_error_break to debug

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Arrangement was not delivered

**Comment by kingroy** [comment]
I merged my branch with Bryn's latest commits and it seems to have fixed this bug.

**Comment by mlesnick** [comment]
Bug is also fixed on my system.
