### ISSUE TITLE
Another Crash in Multicritical Branch 

### ISSUE THREAD

**Issue by mlesnick** [rivetTDA/rivet#96]
This small example (90 points) also causes a crash in the multicritical branch with H0, 30x30 bins.  The crash does not seem to occur every time (about half the time), so might be related to the randomness of the vineyard updates. 

 The console output (-V 8) for this crash is different than for the other crash reported for this branch.  Could be a different problem.

console:  RANDOM VINEYARD UPDATES TO CHOOSE THE INITIAL THRESHOLD 

console:    -->Doing some random vineyard updates... 

libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Arrangement was not delivered
Abort trap: 6

[BCassidy_No_Fun4.txt](https://github.com/rivetTDA/rivet/files/1092612/BCassidy_No_Fun4.txt)

**Comment by kingroy** [comment]
I found a memory leak that has been patched. This leak also seems to have fixed this bug.

**Comment by mlesnick** [comment]
Bug is also fixed on my system.
